### ISSUE TITLE
How do you use it?

### ISSUE THREAD

**Issue by ArielZgo** [Actardnes/homebridge-blebox#13]
Hi, I have an issue using this plugin as there is no info how to add Accessories like shutterbox or air sensor. Could you please share some info on it?

**Comment by Actardnes** [comment]
That's very general question. Accessories like shutterbox or air sensor will be found automatically if they are available in your local network.
Please read  `Configuration` and `Usage` sections in https://github.com/Actardnes/homebridge-blebox/blob/master/README.MD 
It is explained how to use it.

More information about installation [homebridge](https://www.npmjs.com/package/homebridge) on Raspberry Pi you can find: [Install homebridge on raspberry](https://github.com/homebridge/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi)
