### ISSUE TITLE
DimmerBox V2 can't turn off the light

### ISSUE THREAD

**Issue by arkadiush1** [Actardnes/homebridge-blebox#17]
Hi,
Dimmerbox V2 has a problem with turning off (level 0 setting). Device works fine except for the shutdown option. In the video, I compared how V1 (correctly) and V2 (cannot be turned off) work. Device on checked on the application wBox - works correctly. The problem is with Homebridge control.
Is there a chance to fix it? 
Thank you very much in advance!
______________
Device state: {"device":{"deviceName":"DimmerBox_v2","type":"dimmerBox","product":"dimmerBox_v2","hv":"4.3","fv":"0.991","universe":0,"apiLevel":"20200518","iconSet":0,"categories":[1],"id":"96b97e0353a4","ip":"192.168.1.154","availableFv":"0.991"}}
___________________
https://user-images.githubusercontent.com/38531517/131894230-216430d6-6700-4f05-97c2-59985c90826e.mov

**Comment by arkadiush1** [comment]
Hi,
Can anything be done about it?
THX

**Comment by Actardnes** [comment]
Hi, I will try to fix it next week. Currently, I'm very busy.

**Comment by arkadiush1** [comment]
Great!

**Comment by Actardnes** [comment]
fixed in: https://github.com/Actardnes/homebridge-blebox/releases/tag/0.2.1
