### ISSUE TITLE
Blebox integration problem

### ISSUE THREAD

**Issue by Damianod27** [Actardnes/homebridge-blebox#19]
Hello. 

I have two Homebridge bridges. One works on the Raspebrry Pi 4. Where I have never had a problem with your integration. Due to the lack of a Raspberry Pi on the market, I bought an Orange Pi Zero computer. I have 9 integrations installed here. I only have a problem with the Blebox plug. I don't know anything about it, so I am asking you for help. I am attaching a screenshot of my system and the log where the problem is. Thank you for any help. 

Regards Damian

![Zrzut ekranu 2021-10-11 030513](https://user-images.githubusercontent.com/79320859/136720149-c31e91cd-b2b8-4d87-94f2-0dfc94208180.png)
![Zrzut ekranu 2021-10-11 030927](https://user-images.githubusercontent.com/79320859/136720151-890cda5b-e928-4b8e-a897-d654765f8c37.png)

**Comment by Actardnes** [comment]
Hi,
1. What version of integration are you using?
2. Could you show me a response for http://192.168.8.111/api/device/state

**Comment by Damianod27** [comment]
Hello 

I am using version v.0.2.1. 


Receives 
{"device":{"deviceName":"PixelBox","type":"wLightBox","product":"pixelBox","hv":"pixelBox.1.0","fv":"0.1016","universe":0,"apiLevel":"20200229","id":"eefabc3ab549","ip":"192.168.8.111","availableFv":"0.1016"}}

**Comment by Actardnes** [comment]
Should be fixed in 0.2.2. Let me know if it helps.

**Comment by Damianod27** [comment]
Works great !!! Thank you for doing a good job and fixing the problem.
