### ISSUE TITLE
Problem witch plugin

### ISSUE THREAD

**Issue by mkserwis** [Actardnes/homebridge-blebox#3]
Hi,
I have a problem witch start homebridge witch blebox plugin.
Could You see.... maybe You can help ?

[10/14/2017, 9:48:24 PM] Loaded plugin: homebridge-blebox
[10/14/2017, 9:48:24 PM] Registering platform 'homebridge-blebox.BleBoxPlatform'
[10/14/2017, 9:48:24 PM] ---
[10/14/2017, 9:48:24 PM] Loaded config.json with 0 accessories and 1 platforms.
[10/14/2017, 9:48:24 PM] ---
[10/14/2017, 9:48:24 PM] Loading 1 platforms...
[10/14/2017, 9:48:24 PM] [SomePlatformName] Initializing BleBoxPlatform platform...
[10/14/2017, 9:48:24 PM] Loading 0 accessories...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 131-45-155 │     
    └────────────┘     
                       
[10/14/2017, 9:48:24 PM] [SomePlatformName] Searching blebox devices started!
Checking ip: 10.10.10.1
[10/14/2017, 9:48:24 PM] Homebridge is running on port 51826.
Checking ip: 10.10.10.2
Cannot parse: <!DOCTYPE html>
<html>
<head><meta http-equiv="Pragma" content="no-cache"><meta http-equiv="Cache-Control" content="no-cache"><meta http-equiv="Expires" content="0">
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta charset="utf-8" />
<title></title>
<link type="text/css" href="theme/common.css?v=20161206104152" rel="stylesheet" />
<link type="text/css" href="theme/chosen.css?v=20161206104152" rel="stylesheet" />
<link href="favicon.ico" rel="shortcut icon" />
<meta name="viewport" initial-scale="1.0" />

</head>
<body>
	<div id='msgOverlay'>
		<div><span  id='msgDiv'></span></div>
	</div>
	<div id="mainBody-fluid">
	    <div id='topStatus' class="row-fluid">
			<div id='lang'>
            <div id="langLogoBar" class="row-fluid langborder">
                <div class="span4">
                	<img src="img/logo_zte.png" class="paddingleft10"/>
                    <span class="verticalalign" id="webui_title"></span>
				</div>
                <div id="statusBar" class="span8 side-right margintop8" style="display: none;">
                    <span class="statusItem" title="network_type" i18n="true" id="networkType" data-bind="text: networkType"></span>
                    <span class="statusItem" title="network_provider" i18n="true" id="operator" data-bind="text: networkOperator"></span>
                    <span class="statusItem" title="ota_title" i18n="true" id="OTA" data-bind="visible:OTAStatus">
                        <a onclick="return showOTAAlert();">
                            <img class="paddingbottom6" src="./img/update.gif"/>
                        </a>
                    </span>
                    <span class="statusItem" title="signal_strength" i18n="true" id="signal_strength"><i class="signal" data-bind="attr:{'class': signalCssClass}">&nbsp;</i></span>
                    <span class="statusItem" title="connection_status" i18n="true" id="connection_status" data-bind="visible: isShowConnectionIcon"><i class="icon_connection" data-bind="attr:{'class': connectionCssClass}">&nbsp;</i></span>					
                    <span class="statusItem" title="sms_unread_count" i18n="true" id="sms_unread_count" data-bind="visible: smsUnreadCount() > 0 || showSmsDeleteConfirm()" style="display: none;">
                    	<a onclick="return gotoSmsList();" href="javascript: void(0)">
                    		<img data-bind="visible: smsUnreadCount() > 0 && !showSmsDeleteConfirm()" class="paddingbottom6" src="./img/sms_unread.png"/>
                    		<img data-bind="visible: showSmsDeleteConfirm()" class="paddingbottom6" src="./img/sms_full.gif"/>
                    		<span data-bind="visible: smsUnreadCount() > 0, text: smsUnreadCount" class="smsUnreadCount"></span>
                    	</a>
                    </span>
                    <span class="statusItem" title="sim_status" i18n="true" id="statusItemSimStatus"><img data-bind="attr: {src: simStatus}" class="paddingbottom6"/></span>
                    <span class="statusItem" title="roaming_status" i18n="true" id="roamingStatus" data-bind="visible: roamingStatus() == 'R'" style="display: none;"><img class="paddingbottom6" src="./img/roaming.png"/></span>
                    <span class="statusItem" title="wifi_status" i18n="true" id="wifi_status" data-bind="visible: hasWifi"><img class="paddingbottom6" id="wifi_status_img" data-bind="attr: {src: wifiStatusImg}"/></span>
					<span class="statusItem" title="battery_level" i18n="true" data-bind="visible: hasBattery"><img  class="paddingbottom6" id="batteryCharging" data-bind="attr: {src: batteryPers}"/></span>
				</div>
            </div>
            <div class="row-fluid marginbottom5">
                <div id="themeContainer" class="span12 side-right" >
                    <span id="themeSection" style="display: none;">
						<span class="colorBlock default" data-bind="css: {active: currentTheme() == 'style'}, click: function(data, event) { themeClickHandler(data, event, 'style') }">&nbsp;</span>
						
						<span class="colorBlock mac" data-bind="css: {active: currentTheme() == 'mac'}, click: function(data, event) { themeClickHandler(data, event, 'mac') }">&nbsp;</span>
						<link data-bind="attr: {href: themeHref}" rel="stylesheet" id="customTheme" type="text/css"/>
					</span>
					<div class="span6 side-left" id="currentOpMode" data-bind="visible: isLoggedIn">
						<label trans="current_mode"></label>
						<span id="opmode"></span>
						<input id="change" type="button" class="btn-1 " trans="change" data-bind="click: showOpModeWindow, visible: isLoggedIn, enable: enableFlag" style="display:none" />
					</div>
                    <select id="language" class="marginright10" data-bind="options: languages, value: currentLan, optionsText: 'text', optionsValue: 'value', event:{ change: langChangeHandler}"></select>
					<span id="logout">
						<a id="logoutlink" class="logout marginright10" trans="logout" href="javascript:void(0)" data-bind="click:logout,visible:showLogout() " style="display: none;"></a>
				    </span>
                </div>
            </div>
        </div>
    </div>

    <div id='nav' data-bind="visible:showMenu()"  class="row-fluid">
        <ul id="list-nav" data-bind="foreach: mainMenu" class="span12">
            <li data-bind='attr: {mid: hash.substring(1)}'>
            	<a data-bind='attr: {href: hash, trans: hash.substring(1)}'></a>
            </li>
        </ul>
    </div>
    <div class="row-fluid">
        <div id="mainContainer" class="row-fluid">
            <div id='left' class="span3" data-bind='visible: secondMenu().length > 0'>
                <ul id="leftmenu" data-bind="foreach: {data: secondMenu }">
                    <li data-bind="visible: false, text: $root.getThirdMenu($data)"></li>
                    <li data-bind="attr: {'class': 'menu-two-level ' + hash.substring(1) }">
                    	<a data-bind='attr: {href: hash, trans: hash.substring(1)}'></a>
                    </li>
                    <li data-bind='visible: $root.thirdMenu().length > 0' class="hide">
                        <ul class="third" data-bind="foreach: $root.thirdMenu()">
                            <li data-bind="attr: {'class': 'menu-three-level ' + hash.substring(1) }">
                            	<a data-bind='attr: {href: hash, trans: hash.substring(1)}'></a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div id='container' class="span9 paddingnone"></div>
        </div>
    </div>
    <div id='footer' class="side-center">
        <span trans='copyright'></span>&nbsp; <span trans="vertical_bar"></span> &nbsp;<a href="http://opensource.ztedevice.com" target="_blank" trans="open_source_licenses" class="extendLink"></a>
    </div>
</div>
<div id='loading'>
    <div class='header'><span id="loadMsg"></span></div>
    <br/>

    <div style='text-align: center'>
		<div><span id="loading_wording" class="message"></span></div>
        <img id="loadingImg"/>
        <div id="loading_container"></div>
    </div>
</div>

<div id='progress'>
    <div class='header'><span id="barMsg"></span></div>
     <br/>
     <div class="progress-content">
         <div class="progress-bar-container">
             <div id="bar" class="progress-bar"></div>
             <div id="barValue" class="progress-bar-value"></div>
         </div>
         <div id="progress_container" class="progress-prompt"></div>
     </div>
 </div>

<div id='confirm'>
    <div class='header'><span id="popTitle"></span></div>
    <div id="confirm-message-container">
        <div class='icon'><img id='confirmImg'/></div>
        <div class="confirm-message">
            <div class='message'></div>
            <div class='promptDiv hide'>
                <input name="promptInput" id="promptInput" type="text" maxlength="25" class="width190"/><br/>
                <label class="promptErrorLabel colorRed"></label>
            </div>
        </div>
    </div>
    <div class='buttons'>
        <input type="button" class="btn-1 simplemodal-close" id='okbtn' trans='ok'/>
        <input type="button" class="btn-1 " id='yesbtn' trans='yes'/>
        <input type="button" class="btn-1 simplemodal-close" id='nobtn' trans='no'/>
    </div>
</div>
<div id='popupSettingWindow'>
    <div class='header'>
		<p class="tag-popup-close"><a href="javascript:hidePopupSettingWindow();"></a></p>
	</div>
	<div id="htmlContainer"></div>
</div>
<div id="buttom-bubble">
</div>
<script type="text/x-jquery-tmpl" id="newMessagePopTmpl">
    <div class="bubbleItem ${report}" id="${mark}">
        <h3>
			<span trans="${titleTrans}">${title}</span> ${name} <a href="javascript:void(0);" data-targetid="${mark}" class="bubbleCloseBtn"></a>
		</h3>
        <div class="bubbleContainer">
            <div class="bubbleContent">${content}</div>
            <div class="bubbleDatetime">${datetime}</div>
        </div>
    </div>
</script>
<script type="text/javascript" data-main="js/main" src="js/lib/require/require-jquery.js?v=20161206104152"></script>
</body>
</html>

/usr/lib/node_modules/homebridge-blebox/platform/bleboxPlatform.js:178
    switch (deviceInfo.type.toLowerCase()) {
                           ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at BleBoxPlatform.checkSpecificStateAndAddAccessory (/usr/lib/node_modules/homebridge-blebox/platform/bleboxPlatform.js:178:28)
    at Object.onSuccess (/usr/lib/node_modules/homebridge-blebox/platform/bleboxPlatform.js:145:34)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-blebox/common/communication.js:91:27)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

**Comment by Actardnes** [comment]
This problem is fixed by @marepoc516 on master branch.
In next week i will release next version to npm.

**Comment by mkserwis** [comment]
Thank's
I'm waiting.. ;-)

**Comment by Actardnes** [comment]
New version released :)
