### ISSUE TITLE
BleBox Sauna

### ISSUE THREAD

**Issue by FilipK23** [Actardnes/homebridge-blebox#7]
Is it possible to use your plugin with sauna? Homebridge can not find and pair device.

**Comment by Actardnes** [comment]
Currently no, but i will check API for this device and maybe in next week will add this.

**Comment by FilipK23** [comment]
> Currently no, but i will check API for this device and maybe in next week will add this.

Thank you, it will be really helpful.

**Comment by FilipK23** [comment]
@Actardnes do you have some news?

**Comment by Actardnes** [comment]
@FilipK23 
im currently too busy, to setup all environment to test it and i don't have any saunaBox, i could just add this feature but without testing it's risky. 

I found that [`home assistant`](https://www.home-assistant.io) have integration with homekit and blebox (supporting saunaBox)
Maybe you can try to setup this:
https://www.home-assistant.io/integrations/homekit/
https://www.home-assistant.io/integrations/blebox/

Currently it is more common way i think and they support much more.

Anyway if you really want to stay with this plugin for homebridge let me know i will add support for saunaBox, but without testing. You will test it by yourself and then let me know what i should fix.

**Comment by FilipK23** [comment]
It will be much better for me to have all plugins in my homebridge, so could you extend your plugin for saunaBox and I will test it. I could support your work by donate.

**Comment by Actardnes** [comment]
Here is branch with saunabox:
https://github.com/Actardnes/homebridge-blebox/tree/saunabox

If you install homebridge-blebox globally: 
`npm install -g Actardnes/homebridge-blebox#saunabox`

If locally in some directory:
`npm install Actardnes/homebridge-blebox#saunabox`


Please let me know if it is working, so i can make it official on npm repo.

**Comment by FilipK23** [comment]
> Here is branch with saunabox:
> https://github.com/Actardnes/homebridge-blebox/tree/saunabox
> 
> If you install homebridge-blebox globally:
> `npm install -g Actardnes/homebridge-blebox#saunabox`
> 
> If locally in some directory:
> `npm install Actardnes/homebridge-blebox#saunabox`
> 
> Please let me know if it is working, so i can make it official on npm repo.

Hello, thank you. Everithing is working fine but it is not possible to set temerature greather then 380 °C. Sauna box support temperatures up to 1250 °C.
![image](https://user-images.githubusercontent.com/23122574/98452161-1dbc2500-214d-11eb-85ad-b768cde6e594.png)

**Comment by Actardnes** [comment]
ok, i changed it like this:
- display(currently measured) temperature can be: from -30°C to 125°C
- desired/target temperature can be: from 0°C to 125°C 

If u think other ranges for temperature will be better let me know.
Maybe for desired/target temperature: from 40°C to 125°C? (if picker have smaller range then it's easier to select desired value)

**Comment by FilipK23** [comment]
> ok, i changed it like this:
> 
> * display(currently measured) temperature can be: from -30°C to 125°C
> * desired/target temperature can be: from 0°C to 125°C
> 
> If u think other ranges for temperature will be better let me know.
> Maybe for desired/target temperature: from 40°C to 125°C? (if picker have smaller range then it's easier to select desired value)

Thank you everything is working fine. Temperatures are OK. So big thanks.

**Comment by Actardnes** [comment]
ok, now it's official in npm repo with version 0.0.9
