### ISSUE TITLE
wLightBoxs detected as Saunabox?

### ISSUE THREAD

**Issue by niou-ns** [Actardnes/homebridge-blebox#9]
HAP Warning: Characteristic 00000025-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000004A-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic 00000008-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000004A-0000-1000-8000-0026BB765291. Adding anyway.
Cannot add to queue Command undefined, Ip 192.168.1.226, ExtraData: { onSuccess: [Function: onSuccess], onError: [Function: onError] }
[2020-11-16 12:46:28] [Blebox] Added new accessory wlightboxs!
[2020-11-16 12:46:28] [Blebox] Now we have: 2

0.0.8:
![IMG_7376](https://user-images.githubusercontent.com/2974907/99249461-74d78f00-280a-11eb-8862-8a592c407ac7.PNG)

0.0.9
![IMG_7377](https://user-images.githubusercontent.com/2974907/99249457-71dc9e80-280a-11eb-8122-bf99b19ad551.PNG)

**Comment by Actardnes** [comment]
My mistake in code refactor, tomorrow i will release fixed version. Sorry for inconvenience

**Comment by Actardnes** [comment]
fixed in 0.1.0
